remote_theme: pages-themes/cayman@v0.2.0
title: Takumi Sase, Ph.D.
plugins:
 - jekyll-sitemap
 - jekyll-remote-theme
header_pages:
  - index.md
  - edu.md
  - exp.md
  - teach.md
  - res.md
  - pubs.md
  - presents.md
