remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Takumi Sase, Ph.D.
description: Dynamical Systems, Attractors, Brain
google_analytics: [Your Google Analytics tracking ID]
